# Deployed in the first block.
contract_address = "0xc4228701A7B92793b2428687DC37D0ed92e0d7A7"
protocol_chain_polling_interval_in_seconds = 30
epoch_duration = 40 # should be about 10 minutes in Goerli

[protocol_chain]
name = "goerli:0"
jrpc = "goerli_0"

[indexed_chains]
"arbitrum:0"        = "arbitrum_0"
"arbitrum:one"      = "arbitrum_one"
"avalnche:0"        = "avalnche_0"
"boba:0"            = "boba_0"
"clover:0"          = "clover_0"
"fantom:0"          = "fantom_0"
"fuji:0"            = "fuji_0"
"fuse:0"            = "fuse_0"
"kovan:1"           = "kovan_1"
"mainnet:0"         = "mainnet_0"
"matic:0"           = "matic_0"
"mbase:montreal"    = "mbase_montreal"
"mbase:netherlands" = "mbase_netherlands"
"moonbeam:montreal" = "moonbeam_montreal"
"mumbai:0"          = "mumbai_0"
"optimism:0"        = "optimism_0"
"optimism:kovan"    = "optimism_kovan"
"poacore:0"         = "poacore_0"
"poasokol:0"        = "poasokol_0"
"rinkeby:0"         = "rinkeby_0"
"ropsten:0"         = "ropsten_0"
"xdai:0"            = "xdai_0"
"zksync:0"          = "zksync_0"

# "aurora:testnet"
# "binance:ankr"
# "celo:0"
# "celo:alfajores"
# "chapel:0"
# "moonrivr:0"
