steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/the-graph-staging/block-oracle:latest", ".", "-f", "docker/Dockerfile"]

  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/the-graph-staging/block-oracle:latest"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=./docker/block-oracle.deployment.yaml
  - --image=gcr.io/the-graph-staging/block-oracle:latest
  - --location=us-central1-a
  - --cluster=epoch-block-oracle
