steps:

# --------------------------------------------------------------------------------
# Build the container image
# --------------------------------------------------------------------------------
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/block-oracle:$COMMIT_SHA", "-f", "k8s/Dockerfile", "."]

# --------------------------------------------------------------------------------
# Push the container image
# --------------------------------------------------------------------------------
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/block-oracle:$COMMIT_SHA"]

images:
- "gcr.io/$PROJECT_ID/block-oracle:$COMMIT_SHA"
timeout: "3200s"
options:
  machineType: "E2_HIGHCPU_8"
