apiVersion: apps/v1
kind: Deployment
metadata:
  name: block-oracle
  labels:
    app: block-oracle
spec:
  selector:
    matchLabels:
      app: block-oracle
  replicas: 1
  template:
    metadata:
      labels:
        app: block-oracle
    spec:
      containers:
        - name: block-oracle
          image: gcr.io/the-graph-staging/block-oracle:latest
          env:
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: block-oracle
                  key: privatekey
          command: ["./usr/local/bin/block-oracle"]
          args:
            - --config-file=config.toml
            - --subgraph-url=https://api.thegraph.com/subgraphs/name/juanmardefago/block-oracle
            - --owner-private-key="$(PRIVATE_KEY)"
