apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -mainnet
commonLabels:
  variant: staging
resources:
  - ../../base
configMapGenerator:
- name: block-oracle-config
  files:
    - config.toml
patchesStrategicMerge:
  - environment-variables.yaml
